'use strict';
const catalog = [
['1001250772','Bolsa e chinelos em tons de mel','Bolsas e acessórios'],['1001250744','Vestido em crochê natural','Moda'],['1001250762','Afeto à mesa','Casa e mesa'],['1001250773','Bolsa azul com corrente','Bolsas e acessórios'],['1001250767','Conjunto verde','Moda'],['1001250749','Mesa em tons naturais','Casa e mesa'],['1001250780','Bolsa e chinelos entre folhagens','Bolsas e acessórios'],['1001250771','Vestido vermelho','Moda'],['1001250745','Conjunto rosa','Moda'],['1001250746','Top rosa e azul','Moda'],['1001250747','Saída em crochê claro','Moda'],['1001250748','Bolsa com franjas','Bolsas e acessórios'],['1001250750','Vestido azul estampado','Moda'],['1001250751','Top verde com franjas','Moda'],['1001250752','Mesa em verde e amarelo','Casa e mesa'],['1001250753','Bolsa em tom natural','Bolsas e acessórios'],['1001250754','Bolsa listrada','Bolsas e acessórios'],['1001250755','Detalhes em rosa','Moda'],['1001250756','Conjunto branco','Moda'],['1001250757','Bolsa de trama aberta','Bolsas e acessórios'],['1001250758','Conjunto azul','Moda'],['1001250759','Bolsa mostarda','Bolsas e acessórios'],['1001250760','Vestido claro: os detalhes','Moda'],['1001250761','Mesa com delicadeza','Casa e mesa'],['1001250763','Franjas em tom natural','Moda'],['1001250764','Crochê com flores amarelas','Casa e mesa'],['1001250765','Saia rosa','Moda'],['1001250766','Peça redonda em duas cores','Casa e mesa'],['1001250768','Trama clara, vista de costas','Moda'],['1001250770','Detalhes e franjas','Moda'],['1001250774','Detalhes da trama','Moda'],['1001250775','Conjunto rosa: outro olhar','Moda'],['1001250776','Top em tom rosado','Moda'],['1001250777','Bolsa em cores vivas','Bolsas e acessórios'],['1001250778','Conjunto rosa e azul','Moda'],['1001250779','Vestido longo rosa','Moda'],['1001250781','Criação em verde vibrante','Moda']
].map(([id,title,category])=>({id,title,category,src:`assets/fotos/${id}.webp`}));
let currentFilter='Todas',visible=16,currentIndex=0;
const gallery=document.querySelector('#gallery'),lightbox=document.querySelector('#lightbox');
const filtered=()=>catalog.filter(p=>currentFilter==='Todas'||p.category===currentFilter);
function renderGallery(append=false){const products=filtered();const start=append?gallery.children.length:0;if(!append){gallery.replaceChildren();gallery.scrollLeft=0}products.slice(start,visible).forEach((p,index)=>{const b=document.createElement('button');b.type='button';b.className='gallery-item';b.setAttribute('aria-label',`Ver ${p.title}`);const frame=document.createElement('span');frame.className='gallery-photo';const img=document.createElement('img');img.width=1000;img.height=1500;img.src=p.src;img.alt=p.title;img.loading='lazy';img.decoding='async';frame.append(img);const tag=document.createElement('small');tag.textContent=p.category;const title=document.createElement('h3');title.textContent=p.title;b.append(frame,tag,title);b.addEventListener('click',()=>{openPhoto(index+start)});gallery.append(b)});document.querySelector('#gallery-count').textContent=`${products.length} criações`;document.querySelector('#load-more').hidden=visible>=products.length}
function setFilter(value){currentFilter=value;visible=16;document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter===value;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});renderGallery()}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));
document.querySelectorAll('[data-category]').forEach(a=>a.addEventListener('click',()=>setFilter(a.dataset.category)));
document.querySelector('#load-more').addEventListener('click',()=>{const previous=visible;visible+=12;renderGallery(true);gallery.children[previous]?.focus({preventScroll:true})});
function showPhoto(){const products=filtered(),p=products[currentIndex];document.querySelector('#prev-photo').disabled=currentIndex===0;document.querySelector('#next-photo').disabled=currentIndex===products.length-1;photoTrack.querySelectorAll('.photo-slide').forEach((slide,index)=>slide.setAttribute('aria-hidden',String(index!==currentIndex)));document.querySelector('#detail-title').textContent=p.title;document.querySelector('#photo-position').textContent=`${String(currentIndex+1).padStart(2,'0')} / ${products.length} · ${p.category}`;document.querySelector('#photo-contact').href='https://wa.me/556292300002?text='+encodeURIComponent(`Olá, Maria! Gostaria de um orçamento para uma peça inspirada nesta criação: ${p.title}. Referência: ${p.id}.\nhttps://ateliêmariarodrigues.com.br/${p.src}\nPodemos conversar sobre cores e medidas?`)}
const photoTrack=document.querySelector('#photo-track');
const motion=()=>matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth';
function openPhoto(index){
  currentIndex=index;
  photoTrack.replaceChildren(...filtered().map((p,i)=>{
    const slide=document.createElement('div');slide.className='photo-slide';
    slide.setAttribute('role','group');slide.setAttribute('aria-label',`${i+1} de ${filtered().length}: ${p.title}`);
    const img=document.createElement('img');img.src=p.src;img.alt=p.title;img.width=1000;img.height=1500;img.draggable=false;img.loading=Math.abs(i-index)<=1?'eager':'lazy';
    slide.append(img);return slide;
  }));
  lightbox.showModal();lightbox.querySelector('.lightbox-scroll').scrollTop=0;document.body.style.overflow='hidden';
  photoTrack.scrollTo({left:currentIndex*photoTrack.clientWidth,behavior:'instant'});showPhoto();
}
function movePhoto(direction){const next=Math.max(0,Math.min(filtered().length-1,currentIndex+direction));photoTrack.scrollTo({left:next*photoTrack.clientWidth,behavior:motion()})}
document.querySelector('#prev-photo').addEventListener('click',()=>movePhoto(-1));
document.querySelector('#next-photo').addEventListener('click',()=>movePhoto(1));
lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();movePhoto(-1)}if(e.key==='ArrowRight'){e.preventDefault();movePhoto(1)}});
let scrollFrame=0;
photoTrack.addEventListener('scroll',()=>{if(scrollFrame)return;scrollFrame=requestAnimationFrame(()=>{scrollFrame=0;const index=Math.max(0,Math.min(filtered().length-1,Math.round(photoTrack.scrollLeft/photoTrack.clientWidth)));if(index!==currentIndex){currentIndex=index;showPhoto()}})},{passive:true});
new ResizeObserver(()=>{if(lightbox.open)photoTrack.scrollTo({left:currentIndex*photoTrack.clientWidth,behavior:'instant'})}).observe(photoTrack);
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').addEventListener('click',()=>d.close());d.addEventListener('close',()=>{document.body.style.overflow=''});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');function closeMenu(){menu.setAttribute('aria-expanded','false');nav.classList.remove('open')}menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});
document.querySelector('#quote-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const lines=[`Olá, Maria! Meu nome é ${data.get('nome').trim()} e gostaria de um orçamento.`,`Peça: ${data.get('peca')}`];for(const [key,label]of [['cores','Cores'],['medidas','Tamanho ou medidas'],['quantidade','Quantidade'],['data','Data desejada'],['ideia','Minha ideia']]){let value=String(data.get(key)||'').trim();if(value){if(key==='data')value=value.split('-').reverse().join('/');lines.push(`${label}: ${value}`)}}const url='https://wa.me/556292300002?text='+encodeURIComponent(lines.join('\n'));window.open(url,'_blank','noopener,noreferrer');const status=document.querySelector('#form-status');status.replaceChildren(document.createTextNode('Sua mensagem está pronta. Se o WhatsApp não abriu, '));const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='toque aqui para continuar';a.style.textDecoration='underline';status.append(a,document.createTextNode('.'))});
document.querySelector('#year').textContent=new Date().getFullYear();
let installPrompt;const installButton=document.querySelector('#install-button');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;installButton.hidden=false});installButton.addEventListener('click',async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installButton.hidden=true});window.addEventListener('appinstalled',()=>{installButton.hidden=true;installPrompt=null});document.querySelector('#install-help').addEventListener('click',()=>{document.querySelector('#install-dialog').showModal();document.body.style.overflow='hidden'});
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{/* O site continua disponível se o navegador impedir o modo offline. */}))}renderGallery();
